# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "292cd1cf3d9f00f3dfddcc8232495bb3"
name = "AutoDiscount"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
